followers/urls.py
from django.urls import path
from .views import follow_view, get_followers_view, get_following_view

app_name = 'followers'

urlpatterns = [
    path('<str:username>/follow', follow_view , name='follow'),
    path('<str:username>/followers-list', get_followers_view , name='followers_list'),
    path('<str:username>/following-list', get_following_view , name='following_list'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import generate_thumbnail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('followers/', include('followers.urls', namespace='followers')),
    path('interactions/', include('interactions.urls', namespace='interactions')),
    path('thumbnail/<str:size>/<path:path>', generate_thumbnail, name='generate_thumbnail'),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index_view , name='index'),
    path('create/', views.post_create_view , name='create'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('update/', views.update_profile_view , name='update'),
    path('change_password/', views.change_password_view , name='change_password'),
    path('suggested_users/', views.suggested_users_view , name='suggested_users'),
    path('<str:username>/', views.profile_view , name='profile'),
]

profiles/models.py
from django.db import models
from myapp.utils.helper_utils import generate_unique_folder_name
from myapp.utils.image_utils import validate_image_size, resize_image
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from typing import Any

class Profile(models.Model):
    def upload_path(self, filename:str) -> str:
        return f"profiles/{self.user.id}/{generate_unique_folder_name()}/{filename}"

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')     
    cover_image = models.ImageField(upload_to=upload_path, blank=True, null=True, validators=[validate_image_size])
    profile_image = models.ImageField(upload_to=upload_path, blank=True, null=True, validators=[validate_image_size])
    bio = models.CharField(max_length=1000, blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.user.username
    
    def save(self, *args: Any, **kwargs: Any) -> None:
        if self.cover_image:
            new_image = resize_image(self.cover_image, (900,))
            self.cover_image = new_image
        if self.profile_image:
            new_image = resize_image(self.profile_image, (150,))
            self.profile_image = new_image    
        return super().save(*args, **kwargs)

@receiver(post_save, sender=User)
def _create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user = instance)

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from typing import Any
import os, shutil
from myapp.utils.helper_utils import remove_image_file

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']    

    bio = forms.CharField(required=False)
    profile_image = forms.ImageField(required=False)
    cover_image = forms.ImageField(required=False)    

    def save(self, commit: bool = ...) -> Any:
        user = super(UserProfileForm, self).save(commit=False)

        old_profile_image = user.profile.profile_image
        old_cover_image = user.profile.cover_image
        
        if self.cleaned_data.get('profile_image'):
            user.profile.profile_image = self.cleaned_data.get('profile_image')
        if self.cleaned_data.get('cover_image'):
            user.profile.cover_image = self.cleaned_data.get('cover_image')
        if self.cleaned_data.get('bio'):
            user.profile.bio = self.cleaned_data.get('bio')

        if commit:
            # Remove old images after new ones are successfully saved
            if self.cleaned_data.get('profile_image') and old_profile_image:
                remove_image_file(old_profile_image)

            if self.cleaned_data.get('cover_image') and old_cover_image:
                remove_image_file(old_cover_image)
            
            user.save()
            user.profile.save() 
        return user

    

profiles/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from .forms import UserProfileForm
from posts.models import Post
from followers.models import Follower
from django.db.models import Q, Exists, OuterRef

@login_required
def update_profile_view(request: HttpRequest) -> HttpResponse:
    user = request.user
    form = UserProfileForm(instance=user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user)

        if form.is_valid():
            form.save(commit=True)

            return render(request, 'profiles/update.html', {
                'form': form,
                'message': 'Profile updated successfully'
            })

    return render(request, 'profiles/update.html', {'form': form})

@login_required
def change_password_view(request: HttpRequest) -> HttpResponse:
    user = request.user
    form = PasswordChangeForm(user)

    if request.method == 'POST':
        form = PasswordChangeForm(user, request.POST)

        if form.is_valid():
            print('valid form')
            form.save(commit=True)

            return render(request, 'profiles/change_password.html',{'form': form, 'message': 'Password has been changed!'})
        
    return render(request, 'profiles/change_password.html',{'form': form})
 
@login_required
def profile_view(request: HttpRequest, username:str) -> HttpResponse:
    user = User.objects.get(username=username)
    posts = Post.objects.filter(author=user).order_by('-created_at')
    is_followed = Follower.objects.filter(followed_by=request.user, following=user).exists()
    return render(request, 'profiles/index.html', {"user":user, "posts": posts, "is_followed": is_followed})

@login_required
def suggested_users_view(request: HttpRequest) -> HttpResponse:
    user = request.user

    followers = Follower.objects.filter(followed_by=user)
    usersToExclude = [follower.following.id for follower in followers]

    users = User.objects.exclude(Q(pk__in=usersToExclude) | Q(pk=user.id)).annotate(
        following_you = Exists(Follower.objects.filter(followed_by=OuterRef('pk'), following=user))
    ).order_by('username')

    return render(request, 'profiles/users.html', {"users": users})

profiles/templates/profiles/index.html
{% extends '_base.html' %}

{% block title %}
  Socio App | {{ user.username }}'s Profile
{% endblock %}

{% block body %}
  <div class="max-w-5xl p-4 sm:px-6 lg:px-8 sm:py-10 space-y-6">
    <div>
      {# Cover image #}
      <div class="w-full h-40 md:h-60 bg-gray-200 rounded-lg overflow-hidden">
        {% if user.profile.cover_image %}
          <img src="{{ user.profile.cover_image.url }}" class="object-cover w-full h-full rounded-lg" alt="{{ user.username }} Cover Image" />
        {% endif %}
      </div>

      <div class="flex flex-col justify-center cursor-pointer -mt-20 px-4">
        {# Profile image #}
        <div class="w-32 h-32 rounded-full bg-gray-300 border-4 border-white flex justify-center items-center">
          {% include 'components/profile-picture.html' with user=user editable=False %}
        </div>

        {# User info #}
        <div class="flex flex-col gap-2 md:flex-row justify-between md:items-center">
          <div>
            {% if user.first_name %}
              <h2 class="text-2xl font-semibold text-gray-900">{{ user.first_name }} {{ user.last_name }}</h2>
              <p class="text-sm text-gray-500">@{{ user.username }}</p>
            {% else %}
              <h2 class="text-2xl font-semibold text-gray-900">@{{ user.username }}</h2>
            {% endif %}
          </div>

          {# Action buttons #}
          <div class="self-end">
            {% if not request.user == user %}
              {% include 'components/follow-button.html' with user=user is_followed=is_followed %}
            {% else %}
              <a href="{% url 'profiles:update' %}" class="cursor-pointer border-emerald-600 border-2 text-emerald-600 hover:bg-emerald-600 hover:text-white px-4 py-1 rounded-lg">Update profile</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {# Bio #}
    {% if user.profile.bio %}
      <p class="text-gray-700">{{ user.profile.bio }}</p>
    {% endif %}

    {# Stats #}
    <div class="flex justify-between w-full md:w-3/5 mx-auto">
      <div class="flex flex-col items-center">
        <span class="text-lg font-semibold text-gray-900 posts-count">{{ user.post.count }}</span>
        <span class="text-sm text-gray-500">Posts</span>
      </div>
      <button type="button" class="flex flex-col items-center get-followers-btn modal-toggler" data-modal-target="followers-modal" data-modal-toggle="followers-modal" data-url="{% url 'followers:followers_list' user.username %}" data-title="Followers">
        <span class="text-lg font-semibold text-gray-900 followers-count">{{ user.following.count }}</span>
        <span class="text-sm text-gray-500">Followers</span>
      </button>
      <button class="flex flex-col items-center get-followers-btn modal-toggler" data-modal-target="followers-modal" data-modal-toggle="followers-modal" data-url="{% url 'followers:following_list' user.username %}" data-title="Followings">
        <span class="text-lg font-semibold text-gray-900 followings-count">{{ user.follower.count }}</span>
        <span class="text-sm text-gray-500">Following</span>
      </button>
    </div>

    {# posts #}
    <section class="max-w-xl">
      <h2 class="text-lg md:text-2xl font-semibold text-gray-900 mb-4">Posts</h2>
      <div class="posts-container space-y-4">
        {% for post in posts %}
          {% include 'components/post-card.html' with post=post showFollowButton=False %}
        {% empty %}
          <div class="posts-empty-container">
            {% if request.user == user %}
              {% include 'components/create-post-button.html' with text='Create your first post' %}
            {% else %}
              <p class="text-gray-500">No posts yet</p>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    </section>
  </div>

  <div id="followers-modal" tabindex="-1" class="hidden bg-black/70 overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-full max-h-full" data-type="followers">
    <div class="relative p-4 w-full max-w-md max-h-full post-modal-inner">
      <!-- Modal content -->
      <div class="relative bg-white rounded-lg shadow">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t">
          <h3 class="text-lg font-semibold text-gray-900 modal-title">Followers</h3>
          <button type="button" class="modal-toggler text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-toggle="followers-modal">
            <svg class="w-3 h-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="p-4 md:p-5 followers-container"></div>
      </div>
    </div>
  </div>
{% endblock %}

profiles/templates/profiles/update.html
{% extends '_base.html' %}

{% block title %}
  Socio App | Update {{ user.username }}'s Profile
{% endblock %}

{% block body %}
  <div class="max-w-5xl p-4 sm:px-6 lg:px-8 sm:py-10 space-y-4">
    <div class="flex justify-between gap-2">
      <a href="{% url 'profiles:profile' request.user.username %}" class="text-emerald-700 hover:underline flex items-center">
        <svg class="w-5 h-5 text-inherit" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12l4-4m-4 4 4 4" />
        </svg>Back to profile
      </a>

      <a href="{% url 'profiles:change_password' %}" class="text-emerald-700 hover:underline flex items-center">
        Change password<svg class="w-5 h-5 text-inherit" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 12H5m14 0-4 4m4-4-4-4" />
        </svg>
      </a>
    </div>
    <form class="space-y-4 md:space-y-6" action="{% url 'profiles:update' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div>
        {# Cover image #}
        <label for="cover_image" class="block cursor-pointer w-full h-40 md:h-60 bg-gray-200 rounded-lg overflow-hidden file-input-group" data-removable="false">
          <input type="file" name="cover_image" id="cover_image" class="hidden file-input" />
          {% with cover_image=user.profile.cover_image %}
            <img data-default="{% if cover_image %}
                {{ cover_image.url }}
              {% endif %}"
              src="{% if cover_image %}
                {{ cover_image.url }}
              {% endif %}"
              class="file-placeholder object-cover w-full h-full rounded-lg {% if not cover_image %} hidden {% endif %}" />
          {% endwith %}
        </label>
        {# Profile image #}
        <label for="profile_image" class="flex justify-center cursor-pointer -mt-16 file-input-group">
          <input type="file" name="profile_image" id="profile_image" class="hidden file-input" />
          <div class="w-32 h-32 rounded-full bg-gray-300 border-4 border-white flex justify-center items-center">
            {% with profile_image=user.profile.profile_image %}
              <img data-default="{% if profile_image %}
                  {{ profile_image.url }}
                {% endif %}"
                src="{% if profile_image %}
                  {{ profile_image.url }}
                {% endif %}"
                class="file-placeholder object-cover w-full h-full rounded-full {% if not profile_image %} hidden {% endif %}" />

              <svg class="text-gray-500 w-full file-icon {% if profile_image %} hidden {% endif %}" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" xml:space="preserve">
                <g>
                  <g>
                    <path d="M80,71.2V74c0,3.3-2.7,6-6,6H26c-3.3,0-6-2.7-6-6v-2.8c0-7.3,8.5-11.7,16.5-15.2c0.3-0.1,0.5-0.2,0.8-0.4c0.6-0.3,1.3-0.3,1.9,0.1C42.4,57.8,46.1,59,50,59c3.9,0,7.6-1.2,10.8-3.2c0.6-0.4,1.3-0.4,1.9-0.1c0.3,0.1,0.5,0.2,0.8,0.4C71.5,59.5,80,63.9,80,71.2z" />
                  </g>
                  <g>
                    <ellipse cx="50" cy="36.5" rx="14.9" ry="16.5" />
                  </g>
                </g>
              </svg>
            {% endwith %}
          </div>
        </label>
      </div>

      {% if form.non_field_errors %}
        <div class="p-4 my-2 text-sm text-red-800 rounded-lg bg-red-50" role="alert">
          <ul>
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}

      {% if message %}
        {% include 'components/alert.html' with message=message category='green' type='Success' %}
      {% endif %}

      <div class="block md:flex space-x-2">
        <div class="w-full">
          <input type="text" name="first_name" id="first_name" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:outline-none focus:ring-emerald-500 focus:border-emerald-500" placeholder="First name" value="{{ form.first_name.value|default_if_none:'' }}" />
          {% include 'components/input-error-label.html' with errors=form.first_name.errors %}
        </div>
        <div class="w-full">
          <input type="text" name="last_name" id="last_name" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:outline-none focus:ring-emerald-500 focus:border-emerald-500" placeholder="Last name" value="{{ form.last_name.value|default_if_none:'' }}" />
          {% include 'components/input-error-label.html' with errors=form.last_name.errors %}
        </div>
      </div>
      <div>
        <input type="text" name="username" id="username" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:outline-none focus:ring-emerald-500 focus:border-emerald-500" placeholder="username" required="" value="{{ form.username.value|default_if_none:'' }}" />
        {% include 'components/input-error-label.html' with errors=form.username.errors %}
      </div>
      <div>
        <input type="email" name="email" id="email" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:outline-none focus:ring-emerald-500 focus:border-emerald-500" placeholder="john@example.com" required="" value="{{ form.email.value|default_if_none:'' }}" />
        {% include 'components/input-error-label.html' with errors=form.email.errors %}
      </div>
      <div>
        <textarea name="bio" id="bio" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:outline-none focus:ring-emerald-500 focus:border-emerald-500" placeholder="Tell us about yourself ...">{{ form.bio.value|default_if_none:'' }}</textarea>
        {% include 'components/input-error-label.html' with errors=form.bio.errors %}
      </div>
      <button type="submit" class="w-full text-white bg-emerald-600 hover:bg-emerald-700 focus:ring-4 focus:outline-none focus:ring-emerald-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Update Info</button>
    </form>
  </div>
{% endblock %}

profiles/templates/profiles/users.html
{% extends '_base.html' %}

{% block title %}
  Socio App | Users List
{% endblock %}

{% block body %}
  <div class="max-w-5xl p-4 sm:px-6 lg:px-8 sm:py-10 space-y-4">
    {% if users %}
      <div class="grid grid-cols-[repeat(auto-fill,minmax(16rem,1fr))] gap-x-4 gap-y-6">
        {% for user in users %}
          <div class="rounded-3xl overflow-hidden shadow-xl bg-white flex items-center flex-col">
            <div class="w-full h-32 bg-gray-200 rounded-lg overflow-hidden">
              {% if user.profile.cover_image %}
                <img src="{{ user.profile.cover_image.url }}" class="object-cover w-full h-full" alt="{{ user.username }} Cover Image" />
              {% endif %}
            </div>
            <div class="flex justify-center -mt-8 w-20 h-20 rounded-full bg-gray-300 border-4 border-white items-center">
              {% include 'components/profile-picture.html' with user=user editable=False %}
            </div>

            <div class="pt-1 px-4 pb-4 text-center space-y-2">
              <h3 class="text-gray-900 bold font-sans">@{{ user.username }}</h3>

              {% if user.following_you %}
                <p class="text-sm text-gray-500">{{ user.username }} follows you</p>
              {% endif %}

              {% if request.user != user %}
                {% include 'components/follow-button.html' with user=user is_followed=False %}
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p class="text-center text-gray-700">No users found</p>
    {% endif %}
  </div>
{% endblock %}