account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view , name='login'),
    path('register/', views.register_view , name='register'),
    path('logout/', views.logout_view , name='logout'),
    path('update_profile/', views.update_profile_view , name='update_profile'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import generate_thumbnail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('followers/', include('followers.urls', namespace='followers')),
    path('interactions/', include('interactions.urls', namespace='interactions')),
    path('thumbnail/<str:size>/<path:path>', generate_thumbnail, name='generate_thumbnail'),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index_view , name='index'),
    path('create/', views.post_create_view , name='create'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('update/', views.update_profile_view , name='update'),
    path('change_password/', views.change_password_view , name='change_password'),
    path('suggested_users/', views.suggested_users_view , name='suggested_users'),
    path('<str:username>/', views.profile_view , name='profile'),
]

myapp/views.py
from django.http import HttpRequest, HttpResponse
from PIL import Image
from io import BytesIO
from urllib.parse import unquote
from django.conf import settings
from django.core.cache import cache

def generate_thumbnail(request:HttpRequest, size: str, path:str) -> HttpResponse:
    if not size or not path:
        return HttpResponse(f"Both the image path and the size are required", status=400)
    
    path = unquote(path)
    path = settings.PROJECT_DIR + path

    try:
        image = Image.open(path)
    except Exception as e:
        return HttpResponse(f"An error occurred while opening the image: {e}", status=500)

    sizes = size.split('x')

    try:
        width = int(sizes[0])
        height = int(sizes[1]) if len(sizes) > 1 else None
    except Exception as e:
        return HttpResponse(f"An error occurred while parsing the size: {e}", status=500)
    
    if height is None:
        height = int(image.height * width / image.width)

    filename = "_".join(path.split('/')[-4:])
    # generate a cache key for the thumbnail
    cache_key = f"thumbnail_{filename}_{width}x{height}"

    # check if the thumbnail is already in the cache
    cache_thumbnail = cache.get(cache_key)
    if cache_thumbnail:
        print(f"Cache hit for {cache_key}")
        return HttpResponse(cache_thumbnail, content_type=f"image/webp")

    image.thumbnail((width, height))

    thumbnail_io = BytesIO()
    image.save(thumbnail_io, format='webp', quality=90)
    thumbnail_io.seek(0)

    # save the thumbnail in the cache
    cache.set(cache_key, thumbnail_io.getvalue(), timeout=60*60*24) # cache for 24 hours

    return HttpResponse(thumbnail_io, content_type=f"image/webp")
    

myapp/templates/_auth-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Socio App
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'src/styles.css' %}" />
    {% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
  </head>
  <body class="bg-gray-100">
    <main class="bg-gray-50">
      <section class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <div class="w-full bg-white rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0">
          {% block body %}

          {% endblock %}
        </div>
      </section>
    </main>
  </body>
</html>

myapp/templates/_base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Socio App
      {% endblock %}
    </title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    {% comment %} <link rel="stylesheet" href="{% static 'src/styles.css' %}" /> {% endcomment %}
  </head>
  <body class="bg-gray-100">
    <div class="hidden" id="current-user" data-user="{{ request.user }}"></div>
    <button data-drawer-target="main-sidebar" data-drawer-toggle="main-sidebar" aria-controls="main-sidebar" type="button" class="sidebar-toggler inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200">
      <span class="sr-only">Open sidebar</span>
      <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
      </svg>
    </button>
    <aside id="main-sidebar" class="fixed bg-gray-100 top-0 left-0 z-40 p-4 w-64 h-screen overflow-y-auto transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
      <a href="/" id="drawer-navigation-label" class="text-lg font-semibold text-gray-500 uppercase">Socio</a>
      <button type="button" data-drawer-hide="drawer-navigation" aria-controls="drawer-navigation" class="sidebar-toggler text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 sm:hidden absolute top-2.5 end-2.5 inline-flex items-center">
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"></path>
        </svg>
        <span class="sr-only">Close menu</span>
      </button>
      <div class="py-4 overflow-y-auto">
        <ul class="space-y-2 font-medium">
          <li>
            <a href="/" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
              <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 group-hover:text-gray-900" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m4 12 8-8 8 8M6 10.5V19a1 1 0 0 0 1 1h3v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h3a1 1 0 0 0 1-1v-8.5" />
              </svg>
              <span class="ms-3">Home</span>
            </a>
          </li>
          <li>
            <a href="{% url 'profiles:profile' request.user.username %}" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
              <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 group-hover:text-gray-900" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-width="2" d="M7 17v1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1a3 3 0 0 0-3-3h-4a3 3 0 0 0-3 3Zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
              </svg>
              <span class="flex-1 ms-3 whitespace-nowrap">Profile</span>
            </a>
          </li>
          <li>
            {% include 'components/create-post-button.html' with text='New post' %}
          </li>
          <li>
            <a href="{% url 'profiles:suggested_users' %}" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
              <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 group-hover:text-gray-900" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-width="2" d="M7 17v1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1a3 3 0 0 0-3-3h-4a3 3 0 0 0-3 3Zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
              </svg>
              <span class="flex-1 ms-3 whitespace-nowrap">Find new friends</span>
            </a>
          </li>
          <li>
            <button type="button" data-modal-target="logout-modal" data-modal-toggle="logout-modal" class="modal-toggler flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
              <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 group-hover:text-gray-900" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12H8m12 0-4 4m4-4-4-4M9 4H7a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h2" />
              </svg>
              <span class="flex-1 ms-3 whitespace-nowrap">Logout</span>
            </button>
          </li>
        </ul>
      </div>
    </aside>
    <main class="p-4 sm:ml-64">
      {% block body %}

      {% endblock %}
    </main>
    <!-- Main modal -->
    <div id="new-post-modal" tabindex="-1" class="hidden bg-black/70 overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-full max-h-full">
      <div class="relative p-4 w-full max-w-md max-h-full post-modal-inner">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow">
          <!-- Modal header -->
          <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t">
            <h3 class="text-lg font-semibold text-gray-900">Create New Post</h3>
            <button type="button" class="modal-toggler text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-toggle="new-post-modal">
              <svg class="w-3 h-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
              </svg>
              <span class="sr-only">Close modal</span>
            </button>
          </div>
          <!-- Modal body -->
          <form class="p-4 md:p-5" id="post-form" data-url="{% url 'posts:create' %}">
            {# Error message #}
            {% include 'components/alert.html' with category='red' type='Error' class='post-error-message hidden' %}
            {# Success message #}
            {% include 'components/alert.html' with message='Post added successfully! Thanks for sharing!' category='green' type='Success' class='post-success-message hidden' %}
            {% csrf_token %}
            <div class="grid gap-4 mb-4 grid-cols-1">
              <div class="file-input-group" data-removable="false">
                <input type="file" id="post-image" name="image" class="hidden file-input" />

                <label for="post-image" class="inline-flex items-center justify-center p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 cursor-pointer">
                  <svg class="w-5 h-5 me-1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                    <path fill-rule="evenodd" d="M12 3a1 1 0 0 1 .78.375l4 5a1 1 0 1 1-1.56 1.25L13 6.85V14a1 1 0 1 1-2 0V6.85L8.78 9.626a1 1 0 1 1-1.56-1.25l4-5A1 1 0 0 1 12 3ZM9 14v-1H5a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2h-4v1a3 3 0 1 1-6 0Zm8 2a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H17Z" clip-rule="evenodd" />
                  </svg>Upload Image
                </label>
                <img id="post-image-preview" class="mt-2 border border-gray-300 w-1/2 h-40 object-cover rounded-lg file-placeholder" data-default="{% static 'images/placeholder.png' %}" src="{% static 'images/placeholder.png' %}" alt="Post image" />
              </div>
              <div>
                <textarea id="post-body" name="body" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:outline-none focus:ring-emerald-500 focus:border-emerald-500" placeholder="Write your thoughts..."></textarea>
              </div>
            </div>
            <button type="submit" class="post-form-submit text-white inline-flex items-center bg-emerald-700 hover:bg-emerald-800 focus:outline-none focus:ring-emerald-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
              <svg class="me-1 -ms-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd"></path>
              </svg>Post
            </button>
          </form>
        </div>
      </div>
    </div>

    <!-- Logout alert modal -->
    <div id="logout-modal" tabindex="-1" class="hidden bg-black/70 overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-full max-h-full">
      <div class="relative p-4 w-full max-w-md max-h-full post-modal-inner">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow">
          <!-- Modal header -->
          <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t">
            <h3 class="text-lg font-semibold text-gray-900">Logout Socio</h3>
            <button type="button" class="modal-toggler text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-toggle="logout-modal">
              <svg class="w-3 h-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
              </svg>
              <span class="sr-only">Close modal</span>
            </button>
          </div>
          <!-- Modal body -->
          <form class="p-4 md:p-5" id="logout-form" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <div class="grid gap-4 mb-4 grid-cols-1">
              <div>
                <p class="text-gray-900">Are you sure you want to logout?</p>
              </div>
            </div>

            <div class="flex justify-end items-center gap-2">
              <button type="button" class="bg-gray-200 text-gray-900 hover:bg-gray-300 rounded-lg text-sm px-5 py-2.5 font-medium text-center modal-toggler" data-modal-toggle="logout-modal">Cancel</button>
              <button type="submit" class="text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-emerald-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Logout</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div id="toast" class="hidden min-w-64 max-w-96 text-center rounded p-4 fixed bottom-8 left-[50%] translate-x-[-50%] text-sm font-medium z-50 bg-gray-700 text-white">
      <button type="button" id="toast-close" class="bg-transparenttext-sm absolute top-2.5 end-2.5">
        <svg class="w-3 h-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
        </svg>
        <span class="sr-only">Close toast</span>
      </button>
      <div class="text-left mt-2 mr-3">
        <span id="toast-message">Post created successfully successfully successfully successfully successfully successfully</span>
      </div>
    </div>

    <script src=" https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>