interactions/urls.py
from django.urls import path
from .views import comment_create_view, comment_list_view, comment_delete_view, like_dislike_view

app_name = 'interactions'

urlpatterns = [
    path('<int:post_id>/comments/create', comment_create_view , name='create-comment'),
    path('<int:post_id>/comments/list', comment_list_view , name='list-comments'),
    path('<int:comment_id>/comments/delete', comment_delete_view , name='delete-comment'),
    path('<int:post_id>/likes', like_dislike_view , name='like-unlike'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import generate_thumbnail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('followers/', include('followers.urls', namespace='followers')),
    path('interactions/', include('interactions.urls', namespace='interactions')),
    path('thumbnail/<str:size>/<path:path>', generate_thumbnail, name='generate_thumbnail'),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index_view , name='index'),
    path('create/', views.post_create_view , name='create'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index_view , name='index'),
    path('create/', views.post_create_view , name='create'),
    path('delete/<int:post_id>', views.post_delete_view , name='delete'),
    path('update/<int:post_id>', views.post_update_view , name='update'),
    path('show/<int:post_id>', views.post_show_view , name='show'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('update/', views.update_profile_view , name='update'),
    path('change_password/', views.change_password_view , name='change_password'),
    path('suggested_users/', views.suggested_users_view , name='suggested_users'),
    path('<str:username>/', views.profile_view , name='profile'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from typing import Any
from myapp.utils import image_utils
from myapp.utils.helper_utils import generate_unique_folder_name
from django.dispatch import receiver
from django.db.models.signals import post_delete
from myapp.utils.signal_utils import file_cleanup
import os, shutil
from myapp.utils.helper_utils import remove_image_file

class Post(models.Model):
    def image_upload(self, filename):
        return f"posts/{self.author.id}/{generate_unique_folder_name()}/{filename}"
        
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    body = models.CharField(max_length=500)
    image = models.ImageField(upload_to=image_upload, blank=True, null=True, validators=[image_utils.validate_image_size])
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.id} - {self.author.username} - {self.created_at.strftime('%Y-%m-%d %H:%M:%S')}"

    def save(self, *args: Any, **kwargs: Any) -> None:
        if self.image:
            new_image = image_utils.resize_image(self.image)

            if type(new_image) is dict and new_image.get('status') == 'fail':
                raise ValueError(new_image.get('message'))

            self.image = new_image

        super().save(*args, **kwargs)

    def delete(self, *args: Any, **kwargs: Any) -> tuple[int, dict[str, int]]:
        post = super().delete(*args, **kwargs)    

        if self.image:
            remove_image_file(self.image)

        return post
    
# @receiver(post_delete, sender=Post)
# def _delete_post_image(sender, instance, **kwargs):
#     file_cleanup(instance, 'image')

posts/forms.py
from typing import Any
from django import forms
from .models import Post
import os, shutil
from myapp.utils.helper_utils import remove_image_file

class PostForm(forms.ModelForm):
    body = forms.CharField(max_length=500, required=False)    
    image = forms.ImageField(allow_empty_file=True, required=False)
    clear_image = forms.BooleanField(required=False)

    class Meta:
        model = Post
        fields = [
            'body',
            'image',
            'clear_image'
        ]

    def clean(self) -> dict[str, Any]:
        cleaned_data = super().clean() 

        if self.is_valid():
            if not cleaned_data.get('body') and not cleaned_data.get('image'):
                raise forms.ValidationError("The post must contain either a body or an image")
            
            if not cleaned_data.get('body') and cleaned_data.get('clear_image'):
                raise forms.ValidationError("The post must contain either a body or an image")
        
        return cleaned_data
    
    
    def save(self, commit: bool = ...) -> Any:
        post = super(PostForm, self).save(commit=False)
        old_image = post.image

        if self.cleaned_data.get('body'):
            post.body = self.cleaned_data.get('body')
        if self.cleaned_data.get('image') and self.cleaned_data.get('clear_image') == False:
            post.image = self.cleaned_data.get('image')

        if commit:
            # Remove old images after new ones are successfully saved
            if self.cleaned_data.get('image') and old_image and self.cleaned_data.get('image') != old_image :
                remove_image_file(old_image)
            
            # Remove image if cleared
            if old_image and self.cleaned_data.get('clear_image') == True:
                if post.image:
                    remove_image_file(old_image)
                    post.image.delete()

            post.save()

        return post

    

posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpRequest, HttpResponse, JsonResponse
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.db.models import Exists, OuterRef
from followers.models import Follower
from interactions.models import Like

@login_required
def index_view(request: HttpRequest) -> HttpResponse:
    user = request.user
    posts = Post.objects.order_by('-created_at').annotate(
        is_followed = Exists(
            Follower.objects.filter(
                followed_by = user,
                following = OuterRef('author')
            )
        ),
        is_liked = Exists(
            Like.objects.filter(
                user = user,
                post = OuterRef('pk')
            )
        )
    )[:30]
    return render(request, 'posts/index.html', {"posts": posts})

@login_required
def post_create_view(request: HttpRequest) -> HttpResponse | JsonResponse:
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return render(request, 'components/post-card.html', {"post": post}, content_type='application/html')
        else:
            return JsonResponse({'errors': list(form.errors.values())}, status=400)
    else:
        return JsonResponse({'errors': ['Invalid request method']}, status=405)

@login_required
def post_delete_view(request: HttpRequest ,post_id:int) -> JsonResponse:      
    if request.method == 'POST':
        try: 
            post = Post.objects.get(pk=post_id) 
        except Post.DoesNotExist:
            post = None


        if post and request.user == post.author:
            post.delete()

            return JsonResponse({
                "status": "Success",
                "message": "Post is deleted successfully"
            })

    return JsonResponse({
            "status": "fail",
            "message": "Post couldn't deleted. Try again!"
        })

@login_required
def post_update_view(request: HttpRequest ,post_id:int) -> HttpResponse:
    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        return redirect('/')

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)    

        if form.is_valid():
            form.save(commit=True)

            url = reverse('posts:show', args=[post_id])
            return redirect(url)
    else:
        form = PostForm(instance=post)

    return render(request, 'posts/update.html', {"post": post, "form": form})

@login_required
def post_show_view(request: HttpRequest ,post_id:int) -> HttpResponse:
    try:
        post = Post.objects.annotate(
            is_followed = Exists(
                Follower.objects.filter(followed_by=request.user, following = OuterRef('author'))
            )
        ).get(pk=post_id)

    except Post.DoesNotExist:
        return redirect('/')
    
    return render(request, 'posts/show.html', {"post": post})

posts/templates/components/create-post-button.html
<button type="button" data-modal-target="new-post-modal" data-modal-toggle="new-post-modal" class="modal-toggler flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
  <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 group-hover:text-gray-900" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 5V4a1 1 0 0 0-1-1H8.914a1 1 0 0 0-.707.293L4.293 7.207A1 1 0 0 0 4 7.914V20a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-5M9 3v4a1 1 0 0 1-1 1H4m11.383.772 2.745 2.746m1.215-3.906a2.089 2.089 0 0 1 0 2.953l-6.65 6.646L9 17.95l.739-3.692 6.646-6.646a2.087 2.087 0 0 1 2.958 0Z" />
  </svg>
  <span class="flex-1 ms-3 whitespace-nowrap">{{ text }}</span>
</button>

posts/templates/components/post-card.html
<div class="post-card bg-white w-full rounded-lg shadow-lg post-author-{{ post.author.username }}" id="post-{{ post.id }}">
  <div class="p-4">
    <div class="flex items-center justify-between gap-2">
      <div class="flex items-center gap-4">
        <div class="w-10 h-10 rounded-full bg-gray-300">
          {% include 'components/profile-picture.html' with user=post.author editable=False %}
        </div>
        <div>
          <a href="{% url 'profiles:profile' post.author.username %}" class="block cursor-pointer hover:underline font-medium text-gray-900">{{ post.author.username }}</a>
          <small class="text-xs text-gray-500">{{ post.created_at|date:'M d, Y h:i A' }}</small>
        </div>
      </div>
      {% if not request.user == post.author and showFollowButton == True %}
        {% include 'components/follow-button.html' with is_followed=post.is_followed user=post.author %}
      {% elif request.user == post.author %}
        <div class="relative dropdown-container">
          <button id="post-dropdown-{{ post.id }}" data-dropdown-toggle="post-dropdown-menu-{{ post.id }}" class="dropdown-toggler inline-block text-gray-500 focus:outline-none rounded-lg text-sm p-1.5" type="button">
            <span class="sr-only">Open post settings dropdown</span>
            <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3">
              <path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z" />
            </svg>
          </button>
          <!-- Dropdown menu -->
          <div id="post-dropdown-menu-{{ post.id }}" class="dropdown-menu z-10 hidden absolute right-0 top-6 transition text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44">
            <ul class="py-2" aria-labelledby="post-dropdown-{{ post.id }}">
              <li>
                <a href="{% url 'posts:update' post.id %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-50">Edit</a>
              </li>
              <li>
                <button type="button" data-modal-target="delete-post-{{ post.id }}-modal" data-modal-toggle="delete-post-{{ post.id }}-modal" class="modal-toggler block px-4 py-2 text-sm text-red-600 hover:bg-gray-50 w-full text-left">Delete</button>
              </li>
            </ul>
          </div>
        </div>
      {% endif %}
    </div>

    <!-- Body -->
    {% if post.body %}
      <p class="text-gray-700 my-4">{{ post.body }}</p>
    {% endif %}
  </div>

  <!-- Image -->
  {% if post.image %}
    <div class="relative w-full rounded-b-lg overflow-hidden">
      <picture>
        <!-- Large screens -->
        <source srcset="{% url 'generate_thumbnail' '608' post.image.url|urlencode %}" type="image/webp" media="(min-width: 1024px)" />
        <!-- Ipad screens -->
        <source srcset="{% url 'generate_thumbnail' '474' post.image.url|urlencode %}" type="image/webp" media="(min-width: 768px)" />
        <!-- Mobile screens -->
        <source srcset="{% url 'generate_thumbnail' '348' post.image.url|urlencode %}" type="image/webp" media="(max-width: 640px)" />
        <img class="w-full" src="{{ post.image.url }}" alt="{{ post.author.username }}" />
      </picture>
    </div>
  {% endif %}

  <!-- Actions (Like and Comment) -->
  <div class="flex items-center p-4 border-t gap-4 post-actions">
    <div class="flex items-center text-gray-500 font-medium">
      <button type="button"
        class="text-gray-500 like-btn"
        data-action="{% if post.is_liked %}unlike{% else %}like{% endif %}"
        data-url="{% url 'interactions:like-unlike' post.id %}">
        <svg class="mr-1.5 w-5 h-5 {% if post.is_liked %}text-red-500 fill-red-500{% endif %}" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12.01 6.001C6.5 1 1 8 5.782 13.001L12.011 20l6.23-7C23 8 17.5 1 12.01 6.002Z" />
        </svg>
        <span class="sr-only">Like</span>
      </button>
      <span class="likes-count">{{ post.likes.count }}</span>
    </div>
    <button type="button" type="button" data-modal-target="comment-{{ post.id }}-modal" data-modal-toggle="comment-{{ post.id }}-modal" class="modal-toggler flex items-center text-gray-500 font-medium" data-modal-target="comment-{{ post.id }}-modal" data-modal-toggle="comment-{{ post.id }}-modal">
      <svg class="mr-1.5 w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17h6l3 3v-3h2V9h-2M4 4h11v8H9l-3 3v-3H4V4Z" />
      </svg>
      <span class="comments-count">{{ post.comments.count }}</span>
      <span class="sr-only">Comment</span>
    </button>
  </div>

  <!-- Delete alert modal -->
  <div id="delete-post-{{ post.id }}-modal" tabindex="-1" class="hidden bg-black/70 overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-full max-h-full">
    <div class="relative p-4 w-full max-w-md max-h-full post-modal-inner">
      <!-- Modal content -->
      <div class="relative bg-white rounded-lg shadow">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t">
          <h3 class="text-lg font-semibold text-gray-900">Delete Post</h3>
          <button type="button" class="modal-toggler text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-toggle="delete-post-{{ post.id }}-modal">
            <svg class="w-3 h-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="p-4 md:p-5">
          {% csrf_token %}
          <div class="grid gap-4 mb-4 grid-cols-1">
            <div>
              <p class="text-gray-900">Are you sure you want to delete this post?</p>
            </div>
          </div>

          <div class="flex justify-end items-center gap-2">
            <button type="button" class="bg-gray-200 text-gray-900 hover:bg-gray-300 rounded-lg text-sm px-5 py-2.5 font-medium text-center modal-toggler" data-modal-toggle="delete-post-{{ post.id }}-modal">Cancel</button>
            <button type="button" data-modal-toggle="delete-post-{{ post.id }}-modal" data-post-id="{{ post.id }}" data-url="{% url 'posts:delete' post.id %}" class="delete-post-btn text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-emerald-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Delete</button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Comment modal -->
  {% include 'components/comment-modal.html' with post_id=post.id %}
</div>